export {
  mdiFacebook as facebook,
  mdiTwitter as twitter,
  mdiGithub as github,
  mdiLinkedin as linkedin,
  mdiMapMarker as mapMarker,
  mdiClock as clock,
  mdiQrcode as qr,
  mdiCodeBraces as braces,
  mdiChevronDown as chevron,
  mdiLightbulbOnOutline as lightBulb,
  mdiCogOutline as cog,
  mdiHammerWrench as hammerWrench,
  mdiBus as bus,
} from "@mdi/js";
